// AUTO-GENERATED FROM global.css — DO NOT EDIT MANUALLY
(function injectLDTokens(){
  if (typeof document === "undefined") return; // SSR guard
  var DOC = document;
  var STYLE_ID = "ld-design-tokens";
  if (DOC.getElementById(STYLE_ID)) return;
  var el = DOC.createElement("style");
  el.id = STYLE_ID;
  el.textContent = ":root{--ld-color-primary:#3b82f6;--ld-color-primary-hover:#2563eb;--ld-color-success:#16a34a;--ld-color-success-hover:#15803d;--ld-color-danger:#dc2626;--ld-color-danger-hover:#b91c1c;--ld-color-warning:#d97706;--ld-color-warning-hover:#b45309;--ld-color-info:#0ea5e9;--ld-color-info-hover:#0284c7;--ld-color-text:#111827;--ld-color-text-secondary:#6b7280;--ld-color-text-dark:var(--ld-color-text);--ld-color-background-level0:#ffffff;--ld-color-background-level1:#f8fafc;--ld-color-background-level2:#f1f5f9;--ld-color-border-default:#e5e7eb;--ld-radius-sm:4px;--ld-radius-md:8px;--ld-radius-lg:16px;--ld-radius-xl:20px;--ld-radius-2xl:24px;--ld-shadow-xs:0 1px 2px rgba(0, 0, 0, .06);--ld-shadow-sm:0 1px 3px rgba(0, 0, 0, .10);--ld-shadow-md:0 4px 12px rgba(0, 0, 0, .14);--ld-shadow-lg:0 8px 24px rgba(0, 0, 0, .18);--ld-shadow-xl:0 14px 40px rgba(0, 0, 0, .22);--ld-container-1:448px;--ld-container-2:688px;--ld-container-3:880px;--ld-container-4:1136px;--ld-color-secondary:#1f2937;--ld-color-secondary-hover:#111827;--ld-color-secondary-disabled:#f3f4f6;--ld-color-secondary-disabled-text:#9ca3af;--ld-color-white:#ffffff;--color-primary:var(--ld-color-primary);--color-primary-hover:var(--ld-color-primary-hover);--color-secondary:var(--ld-color-secondary);--color-secondary-hover:var(--ld-color-secondary-hover);--color-secondary-disabled:var(--ld-color-secondary-disabled);--color-secondary-disabled-text:var(--ld-color-secondary-disabled-text);--color-white:var(--ld-color-white);--color-dark-text:var(--ld-color-text);--input-bg:var(--ld-color-background-level0);--input-text:var(--ld-color-text);--input-border:var(--ld-color-border-default);--radius-sm:var(--ld-radius-sm);--radius-md:var(--ld-radius-md);--radius-lg:var(--ld-radius-lg);--shadow-xs:var(--ld-shadow-xs);--shadow-sm:var(--ld-shadow-sm);--shadow-md:var(--ld-shadow-md);--shadow-lg:var(--ld-shadow-lg);--shadow-xl:var(--ld-shadow-xl);--ld-color-divider:#e5e7eb;}[data-theme=\"dark\"]{--ld-color-text:#e5e7eb;--ld-color-text-secondary:#9ca3af;--ld-color-background-level0:#0b0f16;--ld-color-background-level1:#0e0e12;--ld-color-background-level2:#12131a;--ld-color-border-default:#1f2937;--ld-color-secondary:#e5e7eb;--ld-color-secondary-hover:#d1d5db;--ld-color-secondary-disabled:#2a2f3a;--ld-color-secondary-disabled-text:#9ca3af;--ld-shadow-xs:0 1px 2px rgba(0, 0, 0, .50);--ld-shadow-sm:0 1px 3px rgba(0, 0, 0, .60);--ld-shadow-md:0 4px 12px rgba(0, 0, 0, .70);--ld-shadow-lg:0 8px 24px rgba(0, 0, 0, .80);--ld-shadow-xl:0 14px 40px rgba(0, 0, 0, .90);--ld-color-text-dark:var(--ld-color-text);--ld-color-divider:rgba(255,255,255,.12);}";
  DOC.head.appendChild(el);
})();
